services:
  xiaohongshu-mcp:
    image: xpzouying/xiaohongshu-mcp
    container_name: xiaohongshu-mcp
    restart: unless-stopped
    tty: true
    volumes:
      - ./data:/data
    environment:
      - ROD_BROWSER_BIN=/usr/bin/google-chrome
      - COOKIES_PATH=/data/cookies.json
      - IMAGES_PATH=/data/images
    ports:
      - "18060:18060"